package cmd

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

var skillsCmd = &cobra.Command{
	Use:     "skills",
	Aliases: []string{"skill"},
	Short:   "Print the agent skill for this plane-cli build",
	Long: `Print a self-describing SKILL.md for agents.

The command reference is generated from the Cobra command tree of the running
binary, so the skill stays aligned with the exact plane-cli version an agent is
using. The output is Markdown and is designed to be consumed directly from
stdout or redirected to a SKILL.md file.`,
	Args: cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		_, err := fmt.Fprint(cmd.OutOrStdout(), renderSkill(rootCmd))
		return err
	},
}

func renderSkill(root *cobra.Command) string {
	var b strings.Builder

	b.WriteString(`---
name: plane-cli
description: Operate Plane workspaces, projects, work items, Wiki, reports, digests, administration, and raw API workflows through the installed plane-cli binary.
---

# Plane CLI Agent Skill

Use this skill when an agent needs to inspect or operate Plane through ` + "`plane-cli`" + `. This document is generated by the running binary; prefer it over copied documentation when the two disagree.

## Agent operating rules

1. Start with ` + "`plane-cli auth context`" + ` to understand the active principal and scope when authentication state matters.
2. Prefer structured output (` + "`-o json`" + ` or ` + "`-o yaml`" + `) for agent parsing. Do not scrape human-oriented help text when a command returns structured data.
3. Instance-wide tokens may discover multiple workspaces, but workspace-scoped mutations must target one explicit workspace. Never fan out a write unless the user explicitly requested bulk behavior.
4. Resolve human names to IDs/slugs with list/show/member commands before mutation when the target is ambiguous.
5. Prefer first-class commands over ` + "`raw`" + `. Use ` + "`raw`" + ` only as an escape hatch for API operations that do not yet have a dedicated command.
6. For Wiki Markdown, use ` + "`wiki create --file`" + ` / ` + "`wiki update --file`" + ` or ` + "`--markdown`" + `. The CLI sends Markdown source to Plane; do not pre-render it to HTML unless the user explicitly asks to use ` + "`--html`" + `.
7. Treat delete/archive/administrative operations as destructive. Confirm the target from read output before issuing a destructive mutation when the user's request is not already explicit.
8. Use ` + "`plane-cli <command> --help`" + ` for detailed runtime help if a flag or argument is unclear. Re-run ` + "`plane-cli skills`" + ` after upgrading the binary.

## Authentication and configuration

For unattended agents and cron jobs, environment variables are preferred:

` + "```bash" + `
export PLANE_API_HOST=https://work.example.com
export PLANE_API_KEY=plane_iat_xxx
export PLANE_WORKSPACE=workspace-slug   # optional for instance-wide reads
export PLANE_PROJECT=project-id         # optional default project
` + "```" + `

` + "`PLANE_TOKEN`" + ` is also accepted for the token value. ` + "`PLANE_BASE_URL`" + ` remains a compatibility alias for ` + "`PLANE_API_HOST`" + `. Environment variables override config files.

Principal model:
- PAT: user-scoped access according to that user's Plane permissions.
- WSAT: service token bound to one workspace.
- IAT: instance-wide service token. It may enumerate workspaces, but workspace mutations still require an explicit workspace context.

Useful discovery commands:

` + "```bash" + `
plane-cli auth context
plane-cli workspace list -o json
plane-cli workspace members --search alice -o json
plane-cli project list -o json
plane-cli issue list -o json
` + "```" + `

## Common agent workflows

` + "```bash" + `
# Cross-workspace inventory (typically with an IAT)
plane-cli workspace list -o json
plane-cli project list -o json

# Workspace/project reporting
plane-cli --workspace design report summary -o json
plane-cli --workspace design report workload -o json

# Wiki Markdown import
plane-cli --workspace engineering wiki create --name "Runbook" --file ./runbook.md
plane-cli --workspace engineering wiki update <page-id> --file ./runbook.md

# Raw API escape hatch
plane-cli raw GET /workspaces/<slug>/projects/
` + "```" + `

## Global flags

`)

	writeFlags(&b, root.PersistentFlags())
	b.WriteString("\n## Command reference\n\n")
	writeCommandTree(&b, root)

	return b.String()
}

func writeCommandTree(b *strings.Builder, parent *cobra.Command) {
	for _, command := range parent.Commands() {
		if command.Hidden || command.Name() == "help" {
			continue
		}

		fmt.Fprintf(b, "### `%s`\n\n", command.CommandPath())
		short := normalizeSkillText(command.Short)
		long := normalizeSkillText(command.Long)
		if short != "" {
			fmt.Fprintf(b, "%s\n\n", short)
		}
		if long != "" && long != short {
			fmt.Fprintf(b, "%s\n\n", long)
		}
		fmt.Fprintf(b, "Usage: `%s`\n\n", command.UseLine())

		if example := strings.TrimSpace(command.Example); example != "" {
			b.WriteString("Examples:\n\n```bash\n")
			b.WriteString(example)
			b.WriteString("\n```\n\n")
		}

		flags := command.NonInheritedFlags()
		if hasDocumentedFlags(flags) {
			b.WriteString("Local flags:\n")
			writeFlags(b, flags)
			b.WriteString("\n")
		}

		writeCommandTree(b, command)
	}
}

func hasDocumentedFlags(flags *pflag.FlagSet) bool {
	has := false
	flags.VisitAll(func(flag *pflag.Flag) {
		if flag.Name != "help" && !flag.Hidden {
			has = true
		}
	})
	return has
}

func writeFlags(b *strings.Builder, flags *pflag.FlagSet) {
	flags.VisitAll(func(flag *pflag.Flag) {
		if flag.Name == "help" || flag.Hidden {
			return
		}

		name := "--" + flag.Name
		if flag.Shorthand != "" {
			name = "-" + flag.Shorthand + ", " + name
		}
		usage := normalizeSkillText(flag.Usage)
		if usage == "" {
			usage = "No description"
		}
		fmt.Fprintf(b, "- `%s`: %s", name, usage)
		if flag.DefValue != "" && flag.DefValue != "false" && flag.DefValue != "0" {
			fmt.Fprintf(b, " (default `%s`)", flag.DefValue)
		}
		b.WriteString("\n")
	})
}

func normalizeSkillText(value string) string {
	return strings.Join(strings.Fields(value), " ")
}
